spring.application.name=rentvideoII
spring.datasource.url=jdbc:postgresql://localhost:5432/rentvideo
spring.datasource.username=postgres
spring.datasource.password=Exam@cse2311
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=eZMfSI6ulg2W0TBhAuzoXdzrkBq8nQG8I1G+tUVzVyg=
app.jwt.expiration-ms=3600000